# Generated by Django 4.1.5 on 2023-01-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_blogpage_body_remove_blogpage_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homepage",
            old_name="body",
            new_name="bio",
        ),
        migrations.AddField(
            model_name="homepage",
            name="author_name",
            field=models.CharField(default="Francesco Panico", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="tagline",
            field=models.CharField(default="Tech Team Leader", max_length=100),
            preserve_default=False,
        ),
    ]
